import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './tailwind.css'
import Head from 'next/head'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            {/* <Head> */}
            <head>
                <title>Next.js</title>
                {/* </Head> */}
            </head>
            <body className={`${geistSans.variable} `}>{children}</body>
        </html>
    )
}
