import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './tailwind.css'
import PreviewContextProvider from "@/context/PreviewContext";
import SettingsContextProvider from "@/context/SettingsContext";
import UserContextProvider from "@/context/UserContext";
import ConfiguredThemeProvider from "@/theme/ThemeProvider";
import { StyledEngineProvider } from "@mui/material";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} `}>
                <SettingsContextProvider>
                    <UserContextProvider>
                        <ConfiguredThemeProvider>
                            <StyledEngineProvider injectFirst>
                                <PreviewContextProvider>
                                    <>
                                        {children}
                                    </>
                                </PreviewContextProvider>
                            </StyledEngineProvider>
                        </ConfiguredThemeProvider>
                    </UserContextProvider>
                </SettingsContextProvider>
            </body>
        </html>
    )
}
